/* Forge Lesson — curated activity library
   Generated from source; edit this file directly, then run build-standalone.py. */
const LIBRARY=[
  {
    style:"threshold",
    match:["density","float","floating","floats","sink","sinks","sinking","why things float","buoyancy","dense"],
    activityTitle:"Why Ships Float and Nails Sink",
    sort:{"items": ["Steel nail", "Cork", "Marble", "Foam block", "Coin", "Candle wax", "Foil squashed into a ball", "The same foil shaped into a boat"], "task": "Sort them into groups by what they do in water, then find a second way to sort them that cuts across the first — and name the property your second sort is really tracking."},
    poe:{"scenario": "The same square of foil, first squashed into a tight ball, then opened out into a boat shape — both lowered into water.", "tempting": "That both will do the same thing, because it is the same foil and exactly the same weight."},
    counter:{"claim": "Heavy things sink and light things float.", "hunt": "Find something heavy that floats and something light that sinks — then say what the claim should have been about, instead of weight."},
    model:{"build": "Build the same amount of matter packed into two different amounts of space — for example an equal number of marbles in a small box and in a large box.", "test": "Predict which arrangement would float, then check it against the foil ball and the foil boat."},
    liminal:{"looks": ["Keep sorting objects by size, or by how heavy they feel in the hand", "Re-weigh the same object hoping for a different answer", "Abandon the foil boat after one failed attempt and go back to the ball", "Split into two camps and stop testing altogether"], "sounds": ["It's heavy so it sinks.", "But the ship IS heavy, so this doesn't work.", "Can you just tell us the answer?", "Ours floated but it shouldn't have."], "hold": ["Do not supply the word density. Put the contradiction back to them: 'You said heavy sinks. Here is a heavy thing floating. Both are true — what has to change in your idea?'", "Hand them a same-mass pair (foil ball and foil boat) and ask which one their current rule predicts will float.", "Say out loud that being stuck here is the point, and that you expect it to take a while.", "Ask them to write down the rule that is currently failing before they write a new one."]},
    transfer:{"when": "A week later, once packed-ness is stable enough to survive a new context.", "task": "Give a hot-air balloon, an oil spill sitting on water, and a submarine's ballast tanks — none of them a solid dropped into water — and ask students to explain all three with the same single idea.", "lookFor": "Whether they reach for packed-ness compared with the surrounding fluid without prompting, and whether the idea survives moving from solids to a liquid and a gas."},
    progression:{"preliminal": "Explains floating by size or weight alone; treats the steel ship as a trick or an exception.", "liminal": "Knows that weight alone fails and can say why, but flips between explanations and cannot yet predict a new object reliably.", "crossed": "Uses packed-ness compared with water to predict and explain floating for new objects, including the foil ball and the foil boat.", "integrated": "Applies the idea unprompted to unfamiliar fluids and situations, and uses mass and volume together to justify it."},
    troublesome:"Whether something floats has nothing to do with how big or how heavy it is on its own — only with how tightly its matter is packed compared with water.",
    rule:"An object floats when it is less dense than the liquid and sinks when it is denser, whatever its size or total weight; spreading the same mass over more space (trapping air) lowers its density.",
    drivingQuestion:"A steel ship the size of a building floats, but a tiny steel nail sinks — how can the same metal do both?",
    ageBand:"Grade 6 (age 11) · Ages 8–11", totalMinutes:50,
    learningObjective:"Students will be able to explain that whether something floats depends on how tightly its matter is packed compared to water (its density), not on how big or heavy it is, after inventing their own names for the amount of matter, the space it fills, and its 'packed-ness'.",
    keyVocabulary:["mass","volume","density","more/less dense than water"],
    materialsList:["A tub of water","Objects: nail, cork, marble, foam, coin, candle","Aluminium foil","Balance scale","'Our invented words' sheet"],
    lexicon:[
      {slot:"How much matter (stuff) is inside",reveal:"mass"},
      {slot:"How much space it takes up",reveal:"volume"},
      {slot:"How tightly the stuff is packed (heaviness for its size)",reveal:"density"},
      {slot:"Whether it is packed tighter or looser than water",reveal:"more or less dense than water"}
    ],
    engage:{title:"Engage — the floating contradiction",estimatedMinutes:8,materials:["Steel nail","Bowl of water","Picture of a ship"],
      teacherInstructions:`Drop a small steel nail into water — it sinks. Show a photo of a huge steel ship floating. Then float a big piece of foam and sink a small marble. Ask: "It's not about big or small, and not just about heavy or light — so what actually decides whether something floats?" Post the driving question.`},
    explore:{title:"Explore — invent your own words",estimatedMinutes:16,materials:["Assorted objects","Water tub","Balance","'Our invented words' sheet"],
      teacherInstructions:`Groups test objects and INVENT their own made-up word for: (1) how much matter is inside a thing, (2) how much space it takes up, and (3) how tightly that matter is packed for its size. Compare objects that are the same size but different weights, and the same weight but different sizes. They sort floaters and sinkers and describe the rule using ONLY their words. Do NOT give the real terms yet.`},
    explain:{title:"Explain — reveal the real names",estimatedMinutes:12,materials:["Class lexicon chart"],
      teacherInstructions:`Groups share and explain that floating is about how packed a thing is, not its size or weight alone. Build a class chart, then reveal each real term beside the invented one: mass (their matter-word), volume (their space-word), density (their packed-word). State the rule: an object floats when it is LESS dense than water and sinks when it is MORE dense.`},
    elaborate:{title:"Elaborate — the foil boat",estimatedMinutes:9,materials:["Aluminium foil","Water"],
      teacherInstructions:`Give each group a square of foil. Predict-then-check: crush it into a tight ball (sinks) versus shape it into a boat (floats) — the SAME metal and mass. Students explain with their framework that spreading it out over more space (adding trapped air) lowers its density below water. Challenge: how many coins can the boat hold before it sinks?`},
    evaluate:{title:"Evaluate — explain it two ways",estimatedMinutes:5,materials:["Exit slip"],
      teacherInstructions:`Exit ticket: (1) In your invented words AND the real terms, explain why a heavy steel ship floats but a light steel nail sinks. (2) Predict whether a sealed empty bottle will float or sink, and explain why.`}
  },
  {
    style:"threshold",
    match:["circuit","circuits","electric","electricity","light a bulb","battery and bulb","current","series circuit","open circuit","closed circuit"],
    activityTitle:"The Bulb That Needs a Full Loop",
    sort:{"items": ["Bulb touching one battery end", "Bulb wired to both ends", "Two wires meeting in mid-air", "A loop with a gap held open", "A loop with the gap pinched shut", "A loop with a paperclip bridging the gap"], "task": "Sort these arrangements into lights and does not light by predicting first, then testing — and name the single feature that decides which pile each one belongs in."},
    poe:{"scenario": "A working circuit in which one wire is lifted off the battery for two seconds and then put back.", "tempting": "That the bulb will stay lit briefly or fade gradually, because the electricity already inside the wire keeps going."},
    counter:{"claim": "More batteries always make the bulb brighter.", "hunt": "Build a case with two batteries where the bulb does not light at all — then say what the claim left out."},
    model:{"build": "Model the circuit as a ring of students passing a ball hand to hand, with the battery as the one who pushes it along.", "test": "Have one student refuse to pass, then ask whether the ball piles up or the whole loop stops — and check that against the real circuit."},
    liminal:{"looks": ["Touch one wire to the battery and wait for the bulb to light", "Add more wires or a second battery instead of tracing the path", "Swap the bulb, assuming it is broken", "Build a working circuit by accident but cannot rebuild it"], "sounds": ["The electricity comes out of this end and goes into the bulb.", "It needs more power.", "The bulb's dead.", "It worked before, I don't know why."], "hold": ["Do not trace the loop for them. Ask them to point with a finger and narrate the whole journey out loud — stop them at the first gap.", "Give them a deliberately broken circuit and require a prediction before they test it.", "When a group succeeds by accident, take it apart and ask them to rebuild it from their own drawing.", "Ask 'where does it get back to?' rather than 'is it connected?'"]},
    transfer:{"when": "The following week, once tracing the loop has become automatic.", "task": "Give a string of decorative lights with one bulb removed, a torch that has been dropped, and a fridge door light — ask what is broken and why — then have them design a switch for a classroom display.", "lookFor": "Whether they check for a complete return path first, rather than blaming the battery or the bulb."},
    progression:{"preliminal": "Thinks electricity travels out to the bulb and is used up; believes one contact should be enough.", "liminal": "Says the words 'complete circuit' but still troubleshoots by swapping parts rather than tracing the path.", "crossed": "Traces the full loop to diagnose a broken circuit and predicts correctly before testing.", "integrated": "Designs and explains switches and multi-component circuits, reasoning about making and breaking the loop in unfamiliar devices."},
    troublesome:"Touching the wire to the battery is not enough — current only flows when there is a complete, unbroken loop all the way back to the battery.",
    rule:"A bulb lights only when there is a complete (closed) loop for the current, and a switch works by making or breaking that loop.",
    drivingQuestion:"Why won't a bulb light from a battery unless the wire makes a complete loop all the way back?",
    ageBand:"Grade 6 (age 11) · Ages 8–11", totalMinutes:50,
    learningObjective:"Students will be able to explain that a bulb lights only when there is a complete (closed) loop for current, and that a switch works by breaking or completing that loop, after inventing their own names for the push, the flow, and the loop.",
    keyVocabulary:["voltage","current","closed circuit","open circuit / switch"],
    materialsList:["Batteries (with holders)","Small bulbs & holders","Wires with clips","A paperclip switch","'Our invented words' sheet"],
    lexicon:[
      {slot:"The push from the battery that drives the flow",reveal:"voltage"},
      {slot:"The flow that travels around",reveal:"current"},
      {slot:"The unbroken loop it needs",reveal:"closed circuit"},
      {slot:"A gap that stops the flow",reveal:"open circuit / switch"}
    ],
    engage:{title:"Engage — one wire isn't enough",estimatedMinutes:7,materials:["Battery","Bulb","One wire"],
      teacherInstructions:`Connect a battery to a bulb with a SINGLE wire — the bulb stays dark. Ask: "The battery is full of energy and the wire is touching — so why won't it light? What is missing?" Post the driving question and let students puzzle before handing out materials.`},
    explore:{title:"Explore — invent your own words",estimatedMinutes:16,materials:["Batteries","Bulbs","Wires","'Our invented words' sheet"],
      teacherInstructions:`Groups try every arrangement to make the bulb light. When they succeed, they INVENT their own made-up word for: (1) the push coming from the battery, (2) the thing that flows around, and (3) the complete loop that must exist. They also coin a word for a gap that kills the light. Record which set-ups work and which don't, using ONLY their words. Do NOT give the real terms yet.`},
    explain:{title:"Explain — reveal the real names",estimatedMinutes:12,materials:["Class lexicon chart"],
      teacherInstructions:`Groups share and explain that the bulb only lights with an unbroken loop. Build a class chart, then reveal each real term beside the invented one: voltage (their push-word), current (their flow-word), closed circuit (their loop-word), and open circuit / switch (their gap-word). State the rule: current only flows in a complete, closed loop.`},
    elaborate:{title:"Elaborate — add a switch",estimatedMinutes:10,materials:["Paperclip switch","Second bulb"],
      teacherInstructions:`Groups build a paperclip switch and predict what it does before testing — discovering it lights the bulb by CLOSING the loop and turns it off by OPENING it. Extend: add a second bulb in the loop (series) and predict what happens to the brightness and to both bulbs if one is removed.`},
    evaluate:{title:"Evaluate — explain it two ways",estimatedMinutes:5,materials:["Exit slip"],
      teacherInstructions:`Exit ticket: (1) In your invented words AND the real terms, explain why a bulb needs a complete loop to light. (2) A torch stops working when switched off — explain what the switch is doing to the loop.`}
  },
  {
    style:"threshold",
    match:["adjective","adjectives","describing word","describing words","parts of speech","noun and adjective","describing words"],
    activityTitle:"The Words That Change the Picture",
    sort:{"items": ["cracked", "nice", "enormous", "good", "abandoned", "interesting", "frozen", "special"], "task": "Sort these words into ones that change the picture in your head and ones that do not — then say what every word in the useful pile has in common."},
    poe:{"scenario": "The sentence A dog sat by the door, read aloud twice — once with old, shivering added and once with huge, snarling added.", "tempting": "That adding words simply makes the sentence longer or more descriptive, rather than changing what the reader actually sees."},
    counter:{"claim": "Longer and fancier describing words always make writing better.", "hunt": "Find a sentence that gets worse when you add an impressive-sounding adjective — then say what that adjective failed to do."},
    model:{"build": "Draw the picture in your head from a bare sentence, then draw it again after one describing word is added.", "test": "Swap in a different adjective and see whether the drawing has to change — if it does not, the word was doing no work."},
    liminal:{"looks": ["Offer nouns or verbs when asked for describing words", "Add words anywhere in the sentence without checking the effect", "Judge a word by whether it is fancy rather than by what it does", "Spot adjectives in the example but not in their own writing"], "sounds": ["Is 'run' an adjective? It's a good word.", "I put in more describing words — is that enough?", "It's an adjective because it's long."], "hold": ["Do not give the definition. Keep returning to the picture: 'Read me your sentence. Now what did that word change in my head?'", "Offer a word that adds nothing (nice) beside one that changes everything (cracked) and ask which is doing more work.", "Ask them to delete a word and say exactly what was lost.", "Resist correcting a wrong label — ask what job that word is doing instead."]},
    transfer:{"when": "A later lesson, inside real writing rather than word lists.", "task": "Give a deliberately flat paragraph and a mood to create (menacing, joyful, abandoned) and allow them to change only the describing words to hit it.", "lookFor": "Whether they choose words for the picture created rather than for length or fanciness, and whether they can say what each choice changed."},
    progression:{"preliminal": "Labels words as adjectives by feel or by how impressive they sound; may name nouns or verbs instead.", "liminal": "Can pick adjectives out of a given sentence but adds them randomly in own writing without controlling the effect.", "crossed": "Chooses adjectives deliberately to change the reader's picture and can explain what each one changed.", "integrated": "Controls mood and precision in extended writing, and can judge when an adjective is doing no work and should be cut."},
    troublesome:"Meaning lives in the relationship between words: some words exist only to change how you picture another word, so a word's job matters as much as the word itself.",
    rule:"An adjective describes a noun and changes the picture in the reader's mind; adjectives can be added or stacked to sharpen or change that image.",
    drivingQuestion:"What gives some words the power to completely change the picture in your head about another word?",
    ageBand:"Grade 3 (age 8) · Ages 8–11", totalMinutes:40,
    learningObjective:"Students will be able to identify adjectives and explain that they describe nouns and change the picture in the reader's mind, after inventing their own names for naming-words and describing-words.",
    keyVocabulary:["noun","adjective","describe"],
    materialsList:["Word cards (things and describing words)","Drawing paper & crayons","'Our invented words' sheet"],
    lexicon:[
      {slot:"A word that names a person, place, or thing",reveal:"noun"},
      {slot:"A word that describes or 'dresses up' that thing",reveal:"adjective"},
      {slot:"The naming-word that is being described",reveal:"the noun it modifies"}
    ],
    engage:{title:"Engage — the growing picture",estimatedMinutes:7,materials:["Whiteboard"],
      teacherInstructions:`Say "I saw a dog" and have students picture it. Then say "I saw a huge, soggy, three-legged dog." The picture jumps. Ask: "Which words made the picture change? What are those words DOING to the word 'dog'?" Post the driving question.`},
    explore:{title:"Explore — invent your own words",estimatedMinutes:14,materials:["Word cards","Drawing paper","'Our invented words' sheet"],
      teacherInstructions:`Each child draws a plain naming-word (like "cat"). A partner whispers "power words" (fluffy, angry, tiny) and they redraw to match. Groups sort a pile of word cards into two heaps and INVENT their own made-up word for the naming-words and for the picture-changing-words. Use only their words. Do NOT give the real terms yet.`},
    explain:{title:"Explain — reveal the real names",estimatedMinutes:10,materials:["Class chart"],
      teacherInstructions:`Groups share their two word-piles and explain how one kind changes the picture of the other. Build a class chart, then reveal the real terms beside the invented ones: noun (their naming-word) and adjective (their picture-changing-word). Say it simply: adjectives describe nouns.`},
    elaborate:{title:"Elaborate — set the mood",estimatedMinutes:6,materials:["Sentence strips"],
      teacherInstructions:`Give a plain sentence ("The house sat on the hill"). Groups add describing words to make it SPOOKY, then again to make it HAPPY, and notice how the adjectives changed the feeling. Volunteers read both versions.`},
    evaluate:{title:"Evaluate — spot and use",estimatedMinutes:3,materials:["Exit slip"],
      teacherInstructions:`Exit ticket: circle the adjective in "the shiny red car", and write one adjective to describe your own shoe. Quick check that they can spot and use a describing word.`}
  },
  {
    style:"threshold",
    match:["metaphor","simile","figurative","figurative language","figures of speech","literal and figurative","imagery"],
    activityTitle:"When the Classroom Is a Zoo",
    sort:{"items": ["The classroom is a zoo", "She runs like the wind", "He is a rock", "The sky wept", "My bag weighs a tonne", "The lesson was as long as a year"], "task": "Sort these by HOW the comparison is made, not by what they are about — then name the method each group uses."},
    poe:{"scenario": "Reading the classroom is a zoo aloud to someone who has never heard the phrase before, and asking them what it means.", "tempting": "That they will be confused or take it literally, because the sentence is factually false."},
    counter:{"claim": "A metaphor is just a comparison, so any two things can be joined by the word is.", "hunt": "Find a pairing that produces nonsense (the classroom is a spreadsheet) and one that works — then say what the working pair shares that the nonsense pair does not."},
    model:{"build": "Draw two boxes, one for each thing being compared, and a single arrow for the one quality that travels between them.", "test": "List what does NOT travel — no cages, no lions — and check the metaphor still works without it."},
    liminal:{"looks": ["Object that the sentence is simply untrue", "Try to make it literally true (there are no animals here)", "Treat every figurative sentence as a simile", "Explain a metaphor by restating it in the same words"], "sounds": ["But it's not actually a zoo.", "That's just wrong though.", "It means the classroom is a zoo.", "Is it a metaphor if it has 'like' in it?"], "hold": ["Do not resolve the falseness — sit in it: 'You're right, it's false. And everyone still knows exactly what it means. How is that possible?'", "Ask what quality travelled from the zoo to the classroom, and what did NOT travel (no cages, no lions).", "Offer a bad metaphor (the classroom is a spreadsheet) and ask why it fails.", "Let the discomfort of a true-but-false sentence stand rather than explaining it away."]},
    transfer:{"when": "A later lesson, using texts the students did not write.", "task": "Give a song lyric, a line of sports commentary, and a news headline; ask them to name the transferred quality in each, then write a replacement metaphor that transfers a different quality.", "lookFor": "Whether they name the shared quality rather than paraphrasing, and whether they can explain why a weak metaphor fails."},
    progression:{"preliminal": "Treats figurative sentences as errors or lies, or reads them literally.", "liminal": "Accepts that the sentence means something, but explains it by restating it, and confuses metaphor with simile.", "crossed": "Names the quality being transferred and distinguishes metaphor from simile by how the comparison is made.", "integrated": "Creates and evaluates metaphors for effect in own writing, and judges why some comparisons work better than others."},
    troublesome:"A sentence can be literally false yet completely true — figurative language transfers a quality from one thing to another rather than stating a fact.",
    rule:"A metaphor says one thing IS another and a simile says one thing is LIKE another; both work by transferring a shared quality between the two ideas.",
    drivingQuestion:"How can 'the classroom was a zoo' be TRUE when there were no animals in the room?",
    ageBand:"Grade 6 (age 11) · Ages 8–11", totalMinutes:50,
    learningObjective:"Students will be able to tell literal from figurative language and explain how a metaphor or simile transfers a quality from one thing to another, after inventing their own names for say-it-straight language and paint-a-picture language.",
    keyVocabulary:["literal language","figurative language","metaphor","simile"],
    materialsList:["Cards of everyday phrases (literal & figurative)","Chart paper","'Our invented words' sheet"],
    lexicon:[
      {slot:"Language that means exactly what it says",reveal:"literal language"},
      {slot:"Saying one thing IS another to paint a picture",reveal:"metaphor"},
      {slot:"Making the comparison with 'like' or 'as'",reveal:"simile"},
      {slot:"The hidden likeness the two things share",reveal:"the point of comparison"}
    ],
    engage:{title:"Engage — the literal-minded robot",estimatedMinutes:8,materials:["Whiteboard"],
      teacherInstructions:`Write "The classroom was a zoo." Pretend to be a robot that takes it literally and looks around for lions, confused. But every human understood it instantly. Ask: "There were no animals — so how was that sentence still TRUE? What did your brain do with it?" Post the driving question.`},
    explore:{title:"Explore — invent your own words",estimatedMinutes:16,materials:["Phrase cards","'Our invented words' sheet"],
      teacherInstructions:`Groups sort everyday phrases ("time flew", "she's a night owl", "the water was cold", "as brave as a lion") into say-it-straight versus paint-a-picture. They INVENT their own made-up word for language that means exactly what it says, for saying one thing IS another, and for the version that uses "like" or "as". For each picture-phrase they note the hidden likeness. Use only their words. Do NOT give the real terms yet.`},
    explain:{title:"Explain — reveal the real names",estimatedMinutes:12,materials:["Class chart"],
      teacherInstructions:`Groups share and explain that figurative language is not lying — it borrows a quality to make a vivid point. Build a class chart, then reveal the real terms beside the invented ones: literal language, figurative language, metaphor (X IS Y) and simile (X is LIKE Y). Highlight that a metaphor and a simile can carry the same comparison.`},
    elaborate:{title:"Elaborate — transform a sentence",estimatedMinutes:9,materials:["Sentence strips"],
      teacherInstructions:`Give a flat literal sentence ("The test was hard"). Groups rewrite it as a metaphor AND as a simile, then explain the shared quality each one borrows. Share the most vivid ones and discuss which lands best and why.`},
    evaluate:{title:"Evaluate — explain it two ways",estimatedMinutes:5,materials:["Exit slip"],
      teacherInstructions:`Exit ticket: (1) In your invented words AND the real terms, explain how "the classroom was a zoo" can be true. (2) Turn "she ran fast" into a simile and name the quality it borrows.`}
  },
  {
    style:"threshold",
    match:["complete sentence","sentence vs fragment","subject and predicate","fragment","what makes a sentence","subject predicate","complete thought"],
    activityTitle:"When Words Become a Complete Thought",
    sort:{"items": ["Birds sing.", "Running through the tall wet grass at dawn", "The enormous, rusting, half-forgotten ship", "It rained.", "Because she forgot her umbrella", "The cat slept."], "task": "Sort these into finished and leaves you hanging — then say what every item in the finished pile has that the others do not."},
    poe:{"scenario": "A long fragment read aloud, then a two-word sentence read aloud, both with a full stop at the end.", "tempting": "That the longer one will feel more like a sentence, because there is so much more in it."},
    counter:{"claim": "If it starts with a capital and ends with a full stop, it is a sentence.", "hunt": "Find a group of words that has both and still leaves the reader waiting — then say what punctuation cannot fix."},
    model:{"build": "Model each sentence as two cards: a WHO or WHAT card, and a WHAT ABOUT THEM card.", "test": "Try to make both cards for a fragment, and see which card comes up empty."},
    liminal:{"looks": ["Judge completeness by length", "Add a capital and a full stop to a fragment and call it fixed", "Write long run-ons with confidence", "Fix the example but miss the same fault in their own work"], "sounds": ["It's long so it's a sentence.", "I put a capital and a full stop.", "It sounds finished.", "Which bit is missing? It all makes sense to me."], "hold": ["Do not name subject and predicate yet. Read the fragment aloud, stop, and wait — let the unfinished feeling do the work.", "Ask 'who or what, and what about them?' and then stay silent.", "Put a very short complete sentence (Birds sing.) beside a long fragment (running through the tall wet grass at dawn) and ask which is finished.", "Refuse to repair it for them — ask what question the reader is left holding."]},
    transfer:{"when": "A later lesson, applied to their own drafts rather than to given examples.", "task": "Have them audit a piece of their own writing from a previous week, marking every group of words that leaves the reader hanging, and repair each one.", "lookFor": "Whether they test for who/what plus what about them, rather than checking punctuation or counting words."},
    progression:{"preliminal": "Judges sentences by length, punctuation, or whether the words sound interesting.", "liminal": "Senses that something is missing and can say a fragment feels unfinished, but cannot identify what is absent.", "crossed": "Identifies subject and predicate and repairs fragments reliably in given text.", "integrated": "Applies the test unprompted while drafting and editing own writing, including with complex sentences."},
    troublesome:"Interesting words or great length don't make a sentence — a group of words only becomes a complete thought when it has both a subject and a predicate.",
    rule:"A complete sentence needs a subject (who or what) and a predicate (what they are or do); without both it is a fragment that leaves you hanging.",
    drivingQuestion:"When does a pile of words finally become a 'complete thought' you can stop on — and why do fragments leave you hanging?",
    ageBand:"Grade 4 (age 9) · Ages 8–11", totalMinutes:45,
    learningObjective:"Students will be able to explain that a complete sentence needs a subject and a predicate, and fix fragments, after inventing their own names for the who/what part, the doing/being part, and the 'finished' feeling.",
    keyVocabulary:["subject","predicate","complete sentence","fragment"],
    materialsList:["Word-strip piles (subjects and predicates)","Pocket chart or table space","'Our invented words' sheet"],
    lexicon:[
      {slot:"The who or what the words are about",reveal:"subject"},
      {slot:"What that who/what is or does",reveal:"predicate"},
      {slot:"A group of words that feels finished",reveal:"complete sentence"},
      {slot:"A piece that leaves you hanging",reveal:"fragment"}
    ],
    engage:{title:"Engage — the sentence that stops short",estimatedMinutes:7,materials:["Sentence strips"],
      teacherInstructions:`Read aloud, with feeling: "The big red bus..." then stop and wait. The class feels the itch of unfinished-ness. Try "...raced down the hill." Then read a whole one: "The big red bus raced down the hill." Ask: "Why does the last one feel DONE, but the first two leave you hanging?" Post the driving question.`},
    explore:{title:"Explore — invent your own words",estimatedMinutes:15,materials:["Word-strip piles","'Our invented words' sheet"],
      teacherInstructions:`Groups get piles of word-strips and build groups of words, sorting them into "feels finished" and "leaves me hanging." They INVENT their own made-up word for the who/what part, for the doing/being part, and for the finished feeling versus the hanging feeling. They notice what every finished one HAS that the hanging ones lack. Use only their words. Do NOT give the real terms yet.`},
    explain:{title:"Explain — reveal the real names",estimatedMinutes:12,materials:["Class chart"],
      teacherInstructions:`Groups share and explain that a "finished" group of words always has a who/what AND a doing/being part. Build a class chart, then reveal the real terms beside the invented ones: subject, predicate, complete sentence and fragment. State the rule: a complete sentence needs both a subject and a predicate.`},
    elaborate:{title:"Elaborate — rescue the fragments",estimatedMinutes:8,materials:["Fragment cards"],
      teacherInstructions:`Give each group fragment cards (some missing a subject, some missing a predicate). They diagnose which part is missing and fix each one, then underline the subject and circle the predicate, explaining with both invented and real words.`},
    evaluate:{title:"Evaluate — explain it two ways",estimatedMinutes:3,materials:["Exit slip"],
      teacherInstructions:`Exit ticket: (1) Is "Under the old wooden table" a complete sentence? Explain in your invented words AND the real terms. (2) Turn it into a complete sentence and label the two parts.`}
  },
  {
    style:"threshold",
    match:["comma","commas","punctuation","punctuate","comma rules","using commas"],
    activityTitle:"The Comma That Saved Grandma",
    sort:{"items": ["Let's eat Grandma", "Let's eat, Grandma", "I invited my parents, JK Rowling and a clown", "I invited my parents, JK Rowling, and a clown", "She left, happily", "She left happily"], "task": "These come in near-identical pairs. Sort each pair by what actually changes between them — then name the job the comma is doing in each case."},
    poe:{"scenario": "The same list of guests read aloud twice, once with a comma before the final item and once without.", "tempting": "That the comma only changes where you breathe, so the meaning stays exactly the same."},
    counter:{"claim": "You put a comma wherever you would pause for breath.", "hunt": "Find a sentence where the natural pause and the correct comma fall in different places — then say what the comma is really tracking."},
    model:{"build": "Model the sentence as a set of parcels, with commas as the string that decides which words get bundled together.", "test": "Move one comma, re-bundle the parcels, and say exactly who or what changed."},
    liminal:{"looks": ["Sprinkle commas wherever they would pause for breath", "Read both versions of the sentence identically", "Add commas to make writing look more sophisticated", "Delete every comma when unsure"], "sounds": ["You put one where you breathe.", "They mean the same thing.", "I just put them where it looks right.", "Does it even matter?"], "hold": ["Do not give the rules. Make them perform both readings aloud until the two meanings separate audibly, then ask which one the writer wanted.", "Ask 'who is being spoken to here?' for each version.", "Give a sentence where the comma decides who eats and who is eaten, and let them argue it out.", "Do not accept 'it sounds better' — ask what changed in the meaning."]},
    transfer:{"when": "A later lesson, in a context where the ambiguity has real stakes.", "task": "Give ambiguous instructions, a menu, and a text message where a missing comma causes a genuine misunderstanding; ask them to fix each and state both possible meanings.", "lookFor": "Whether they reason about grouping and meaning rather than about pauses or appearance."},
    progression:{"preliminal": "Places commas by breath or by appearance; sees no difference in meaning between the two versions.", "liminal": "Accepts that a comma can change meaning in the demonstration sentence, but reverts to pause-based placement in own writing.", "crossed": "Uses commas to control grouping deliberately in lists, direct address, and joined ideas, and explains the meaning each creates.", "integrated": "Diagnoses and repairs ambiguity in unfamiliar text and makes deliberate punctuation choices for clarity in extended writing."},
    troublesome:"A mark with no sound of its own can change a sentence's meaning by regrouping its words.",
    rule:"A comma groups and separates words to control meaning — separating items in a list, marking who you are speaking to, and splitting two joined ideas.",
    drivingQuestion:"How can one tiny comma change WHO gets eaten in 'Let's eat Grandma'?",
    ageBand:"Grade 5 (age 10) · Ages 8–11", totalMinutes:45,
    learningObjective:"Students will be able to explain how commas change meaning by grouping and separating words, and use them for lists and direct address, after inventing their own names for the pause-mark and its jobs.",
    keyVocabulary:["comma","separating items","direct address","separating clauses"],
    materialsList:["Sentence cards with no commas","Whiteboard","'Our invented words' sheet"],
    lexicon:[
      {slot:"The little mark that makes a reader pause and group words",reveal:"comma"},
      {slot:"Keeping the items of a list apart",reveal:"separating items"},
      {slot:"Showing who you are talking TO",reveal:"direct address"},
      {slot:"Splitting two joined ideas so they do not run together",reveal:"separating clauses"}
    ],
    engage:{title:"Engage — dinner with Grandma",estimatedMinutes:7,materials:["Whiteboard"],
      teacherInstructions:`Write "Let's eat Grandma." Let the class react, then add a comma: "Let's eat, Grandma." Then write "I like cooking my family and my pets" and fix it with commas. Ask: "How can a tiny dot with a tail change WHO we're talking about — or save Grandma's life?" Post the driving question.`},
    explore:{title:"Explore — invent your own words",estimatedMinutes:14,materials:["Comma-less sentence cards","'Our invented words' sheet"],
      teacherInstructions:`Groups read comma-less sentences aloud, feel where they naturally pause, and mark those spots. They INVENT their own made-up word for the pause-mark, and words for its different jobs: keeping list items apart, and showing who you are speaking to. They test how a mark in a different spot changes the meaning. Use only their words. Do NOT give the real term yet.`},
    explain:{title:"Explain — reveal the real name",estimatedMinutes:11,materials:["Class chart"],
      teacherInstructions:`Groups share and explain that the little mark groups and separates words to control meaning. Build a class chart, then reveal the real term (comma) beside the invented one, and name its jobs: separating items in a list, marking direct address (talking TO someone), and separating two joined ideas. Anchor each job to an example students found.`},
    elaborate:{title:"Elaborate — two meanings",estimatedMinutes:8,materials:["Ambiguous sentence cards"],
      teacherInstructions:`Give ambiguous comma-less sentences. Groups place commas two different ways to create two different meanings and explain the difference, using both invented and real terms. Share the funniest meaning-changes.`},
    evaluate:{title:"Evaluate — explain it two ways",estimatedMinutes:5,materials:["Exit slip"],
      teacherInstructions:`Exit ticket: (1) Add commas to "After we ate Grandma and I watched a film." and explain what your commas do, in your invented words AND the real term. (2) Write a list of three foods you like, punctuated correctly.`}
  },
  {
    style:"threshold",
    match:["fraction","fractions","numerator","denominator","equivalent fraction","part of a whole","parts of a whole"],
    activityTitle:"Whose Half Is Bigger?",
    sort:{"items": ["Half of an A4 sheet", "Half of a sticky note", "A quarter of an A3 sheet", "Half of this table", "A third of a chocolate bar", "A quarter of a much larger chocolate bar"], "task": "Make each of these for real, then sort them from smallest to largest — and explain why your order does not match the order of the fractions."},
    poe:{"scenario": "One group cuts a large sheet in half; another cuts a small sticky note in half. Both halves are then held up side by side.", "tempting": "That the two halves will match, because a half is a half."},
    counter:{"claim": "The bigger the bottom number, the smaller the piece.", "hunt": "Find two cases where a quarter is bigger than a half — then say what the claim forgot to mention."},
    model:{"build": "Model each fraction as a paper strip with its whole always drawn around it, so the whole can never be forgotten.", "test": "Compare two fractions whose wholes are different sizes, and see whether the strips still let you decide."},
    liminal:{"looks": ["Compare fractions by comparing the digits alone", "Insist all halves are equal even when shown unequal wholes", "Cut a shape into unequal parts and still call them halves", "Go quiet when two correct answers appear to conflict"], "sounds": ["A half is always a half.", "But four is bigger than two, so a quarter is bigger.", "We're both right, so someone must have cheated.", "This is a trick question."], "hold": ["Do not say 'it depends on the whole'. Put both halves side by side and ask each group to state what they cut.", "Ask 'half of what?' every single time, and wait for the answer.", "Offer half of a small pizza against a quarter of a huge one, ask which they would rather have, then ask why their number rule failed.", "Let two correct-but-different answers sit unresolved for a while."]},
    transfer:{"when": "A later lesson, once 'half of what?' has become an automatic question.", "task": "Give real comparisons — half of one class's fundraising against a third of another's; a quarter off two differently priced items — and ask which is more, and how they know.", "lookFor": "Whether they ask what the whole is before comparing, and whether they cope with unequal wholes unprompted."},
    progression:{"preliminal": "Compares fractions by the digits alone; believes a half is a fixed amount.", "liminal": "Knows the whole matters in the demonstration but still compares by numerator or denominator when the wholes are not visible.", "crossed": "Asks what the whole is, and compares fractions correctly including when the wholes differ.", "integrated": "Reasons flexibly about parts and wholes in unfamiliar quantitative situations and explains why the same fraction can be different amounts."},
    troublesome:"A fraction is not just 'a number over a number': its size depends entirely on the whole it refers to, so 'a half' is not a fixed amount.",
    rule:"The denominator is how many equal parts the whole is cut into (bigger denominator, smaller parts) and the numerator is how many you take; the same fraction can be different amounts when the wholes differ.",
    drivingQuestion:"You and a friend each got 'half' — so why is your friend's half clearly bigger?",
    ageBand:"Grade 4 (age 9) · Ages 8–11", totalMinutes:50,
    learningObjective:"Students will be able to explain that a fraction describes equal parts of a particular whole, and find equivalent fractions, after inventing their own names for the whole, the parts, and how many are taken.",
    keyVocabulary:["whole","denominator","numerator","equivalent fractions"],
    materialsList:["Paper strips of two different lengths","Scissors","Crayons","'Our invented words' sheet","Two different-sized chocolate bars or cookies (optional)"],
    lexicon:[
      {slot:"The thing you start with and cut up",reveal:"the whole (unit)"},
      {slot:"How many equal pieces you cut it into",reveal:"denominator"},
      {slot:"How many of those pieces you take",reveal:"numerator"},
      {slot:"Two amounts that look different but are the same share",reveal:"equivalent fractions"}
    ],
    engage:{title:"Engage — the unfair half",estimatedMinutes:7,materials:["Two very different-sized strips or bars"],
      teacherInstructions:`Give two students "half" — but hand one a half of a big strip and the other a half of a tiny strip. The class protests that it is unfair. Ask: "You BOTH have a half. So why isn't it the same amount? What is a half actually a half OF?" Post the driving question.`},
    explore:{title:"Explore — invent your own words",estimatedMinutes:16,materials:["Paper strips","Scissors","'Our invented words' sheet"],
      teacherInstructions:`Groups fold and cut paper strips into equal pieces and shade some in. They INVENT their own made-up word for: (1) the whole strip they start with, (2) how many equal pieces they cut it into, and (3) how many pieces they colour. Using only their words, they make several and describe them. Challenge: fold a coloured piece again — can two different-looking amounts be the SAME share? Coin a word for that. Do NOT give the real terms yet.`},
    explain:{title:"Explain — reveal the real names",estimatedMinutes:12,materials:["Class lexicon chart"],
      teacherInstructions:`Groups share their words and explain that the SAME fraction word can mean different amounts when the whole is different. Build a class chart, then reveal each real term beside the invented one: the whole/unit (their start word), denominator (their pieces-word), numerator (their taken-word), and equivalent fractions (their same-share word). Stress that the bottom number tells you how BIG each piece is.`},
    elaborate:{title:"Elaborate — compare and match",estimatedMinutes:10,materials:["Fraction strips of one whole"],
      teacherInstructions:`Two challenges: (1) With halves, thirds and quarters of the SAME whole, order them and explain why more pieces means each piece is smaller. (2) Find equivalent fractions by cutting each piece in two (1/2 = 2/4 = 3/6). Students predict, then check with the strips, using both invented and real words.`},
    evaluate:{title:"Evaluate — explain it two ways",estimatedMinutes:5,materials:["Exit slip"],
      teacherInstructions:`Exit ticket: (1) Explain why 1/2 of one thing can be bigger than 1/2 of another, in your invented words AND the real terms. (2) Write one fraction equal to 1/2 and show why with a drawing.`}
  },
  {
    style:"threshold",
    match:["force","forces","push","pull","balanced","unbalanced","net force","friction","gravity and motion"],
    activityTitle:"The Tug-of-War That Goes Nowhere",
    sort:{"items": ["A book resting on a table", "A rope in a deadlocked tug-of-war", "A ball rolling to a stop", "A car speeding up", "A parachutist falling at a steady speed", "A puck sliding across ice"], "task": "Sort these into motion is changing and motion is staying the same — NOT into moving and still — then say what the forces must be doing in each pile."},
    poe:{"scenario": "Two evenly matched teams pulling on a rope that does not move at all, and then one team letting go.", "tempting": "That nothing is happening while the rope is still, so there are no forces acting on it."},
    counter:{"claim": "If something is moving, there must be a force pushing it along.", "hunt": "Find something moving at a steady speed with no push in the direction it is travelling — then say what the claim confused."},
    model:{"build": "Model each situation with arrows drawn to scale for every push and pull, including the ones that are easy to forget.", "test": "Check whether your arrows cancel — and whether that matches whether the motion is actually changing."},
    liminal:{"looks": ["Say there is no force at all on a stationary object", "Look for a bigger force whenever something moves", "Treat a still object as force-free in their drawings", "Cannot explain why a moving object keeps moving"], "sounds": ["Nothing's pushing it, it's just sitting there.", "It stopped, so the force ran out.", "If both teams pull the same, neither is really pulling.", "Something has to keep pushing it or it'd stop."], "hold": ["Do not state the balanced-forces rule. Ask them to draw every push and pull on the still rope, then keep asking 'and what is that one balanced by?'", "Have two students pull hard and equally, and ask whether the forces are absent or cancelled.", "Ask what would happen the instant one side let go — and why that tells them the forces were there all along.", "Do not rescue the 'force runs out' idea — ask what would have to be true for it to be correct."]},
    transfer:{"when": "A later lesson, in situations with no rope and no tug-of-war.", "task": "Give a book resting on a table, a parachutist at terminal velocity, a car at a constant speed on a motorway, and a puck sliding on ice; ask which have balanced forces and how the motion shows it.", "lookFor": "Whether they infer balance from unchanging motion rather than from stillness — especially for things moving at a steady speed."},
    progression:{"preliminal": "Believes motion requires a continuing force, and that a still object has no forces acting on it.", "liminal": "Can say 'balanced forces' for the tug-of-war but still expects a net force wherever there is movement.", "crossed": "Uses balanced and unbalanced forces to explain both stillness and steady motion, and predicts changes correctly.", "integrated": "Applies the idea to unfamiliar cases including constant-speed motion and friction, linking change in motion to unbalanced force without prompting."},
    troublesome:"Things don't move just because a force acts on them — a still object can have huge forces on it; motion only changes when forces are unbalanced.",
    rule:"An object's motion stays the same when forces are balanced and only changes (speeds up, slows down, or turns) when the forces are unbalanced.",
    drivingQuestion:"In a tug-of-war both teams pull with huge force — so why can the rope stay completely still?",
    ageBand:"Grade 5 (age 10) · Ages 8–11", totalMinutes:50,
    learningObjective:"Students will be able to explain that motion changes only when forces are unbalanced, after inventing their own names for pushes and pulls and the 'winner' of competing forces.",
    keyVocabulary:["force","balanced forces","unbalanced forces","net force","friction"],
    materialsList:["Rope for tug-of-war","Toy cars & books","Rubber bands or spring scales","'Our invented words' sheet","Smooth and rough surfaces"],
    lexicon:[
      {slot:"A single push or pull",reveal:"force"},
      {slot:"When two forces tie and nothing changes",reveal:"balanced forces"},
      {slot:"When one side wins and motion changes",reveal:"unbalanced forces"},
      {slot:"The leftover push after both sides are counted",reveal:"net force"}
    ],
    engage:{title:"Engage — the still rope",estimatedMinutes:7,materials:["Rope","A book"],
      teacherInstructions:`Stage a brief tug-of-war that ends in a stalemate — the rope barely moves. Ask: "Nobody is being lazy — both sides pull as hard as they can, so enormous forces are happening. Why is the rope going NOWHERE?" Then rest a book on the table: "Gravity is pulling it down right now — why doesn't it fall?" Post the driving question.`},
    explore:{title:"Explore — invent your own words",estimatedMinutes:16,materials:["Toy cars","Rubber bands","'Our invented words' sheet"],
      teacherInstructions:`Groups push, pull and tug objects and INVENT their own made-up word for: (1) a single push or pull, (2) the situation where two of them tie and nothing moves, and (3) the situation where one wins and the object changes what it is doing. Using only their words, they record exactly when an object starts moving, speeds up, slows down, or stays put. Do NOT give the real terms yet.`},
    explain:{title:"Explain — reveal the real names",estimatedMinutes:12,materials:["Class lexicon chart"],
      teacherInstructions:`Groups share and explain that motion only changed when the "tie" was broken. Build a class chart, then reveal each real term beside the invented one: force (their push/pull word), balanced forces (their tie word), unbalanced forces (their winner word) and net force (the leftover push). State the rule the students discovered: motion changes only when forces are unbalanced.`},
    elaborate:{title:"Elaborate — predict the motion",estimatedMinutes:10,materials:["Cars","Rough & smooth surfaces"],
      teacherInstructions:`Give simple force pictures (arrows) and have students predict: stay still, speed up, or change direction — and justify with balanced/unbalanced. Then roll a car on a smooth vs a rough surface and discover friction as a hidden force that unbalances motion and slows things down.`},
    evaluate:{title:"Evaluate — explain it two ways",estimatedMinutes:5,materials:["Exit slip"],
      teacherInstructions:`Exit ticket: (1) In your invented words AND the real terms, explain why a book on a table does not move even though gravity pulls it. (2) Draw arrows for a box that is speeding up, and label the forces balanced or unbalanced.`}
  },
  {
    style:"threshold",
    match:["photosynthesis","chlorophyll","how plants make food","plants make food","plant food","glucose","how plants grow","where plants get mass"],
    activityTitle:"Where Does a Tree Come From?",
    sort:{"items": ["Soil", "Water", "Air", "Sunlight", "Fertiliser", "The original seed"], "task": "Sort these into could supply the tree's mass and could not — then rank whatever survives by how much mass it could realistically provide."},
    poe:{"scenario": "A potted plant grown for five years, where both the plant and the dried soil are weighed at the start and at the end.", "tempting": "That the soil will have lost roughly as much mass as the plant gained."},
    counter:{"claim": "Plants get their food and their mass from the soil.", "hunt": "Find the measurement that breaks this claim — then work out, by elimination, where the mass must have come from instead."},
    model:{"build": "Model the plant as a builder and each input as a delivery lorry, sizing every lorry by how much mass it actually delivers.", "test": "Weigh a balloon of carbon dioxide, then check whether the air lorry is really as empty as it looks."},
    liminal:{"looks": ["Return to soil and water no matter what the mass data shows", "Propose that the soil must have been replaced or the scales were wrong", "Accept the term carbon dioxide but keep explaining growth as feeding", "Recite the equation yet cannot say where the mass came from"], "sounds": ["It eats the soil.", "The gardener must have added more soil.", "Air weighs nothing though.", "It gets its food from its roots."], "hold": ["Do not hand them the equation. Return to the mass data: 'The soil lost almost nothing. The tree gained a great deal. Where did it come from?' — then wait through the silence.", "Have them find the mass of a balloon of carbon dioxide, so 'air weighs nothing' has to be given up first.", "Let the absurd-seeming answer be reached by elimination rather than announced by you.", "Ask them to name every place the mass could possibly have come from, then rule them out one at a time."]},
    transfer:{"when": "A later lesson, once mass-from-air is secure.", "task": "Ask where the mass of a burning log goes, where the carbon in a plank of wood originally came from, and what a forest does to the air over a century.", "lookFor": "Whether they track carbon through the system rather than restating the equation, and whether they link plant growth to atmospheric carbon."},
    progression:{"preliminal": "Explains plant growth as feeding on soil, water, or fertiliser; treats air as weightless nothing.", "liminal": "Repeats the photosynthesis equation but still reaches for the soil when asked where the mass came from.", "crossed": "Explains that most of the plant's mass is built from carbon dioxide, using the mass evidence to justify it.", "integrated": "Traces carbon through growth, burning, and the atmosphere, and applies the idea to unfamiliar ecological questions."},
    troublesome:"A tree's mass comes mostly from an invisible gas in the air (carbon dioxide), not from the soil it grows in.",
    rule:"In light, a plant uses carbon dioxide and water to build glucose and release oxygen, so most of its mass is built from the air.",
    drivingQuestion:"A tree can weigh tonnes, yet the soil in its pot barely goes down — so where did all that tree actually come from?",
    ageBand:"Grade 7 (age 12) · Ages 12–14", totalMinutes:55,
    learningObjective:"Students will be able to explain that plants build their own food and mass using light, carbon dioxide and water (not soil), after inventing their own names for the gas taken in, the food-maker, the process and the products.",
    keyVocabulary:["photosynthesis","chlorophyll","carbon dioxide","glucose","oxygen"],
    materialsList:["Pondweed (Elodea) in water","Bright lamp","Beaker & funnel to catch bubbles","Variegated or dark-kept leaves","'Our invented words' sheet"],
    lexicon:[
      {slot:"The invisible gas the plant takes from the air",reveal:"carbon dioxide"},
      {slot:"The green stuff in the leaf that captures light",reveal:"chlorophyll"},
      {slot:"The light-powered food-making process",reveal:"photosynthesis"},
      {slot:"The sugar food the plant builds",reveal:"glucose"},
      {slot:"The gas the plant lets out",reveal:"oxygen"}
    ],
    engage:{title:"Engage — the impossible mass",estimatedMinutes:8,materials:["The van Helmont willow story / a large potted plant"],
      teacherInstructions:`Tell the class about a scientist who grew a tree in a pot for years: the tree gained tens of kilograms, but the soil lost only grams. Ask: "It clearly didn't eat the soil. So where did all that wood and leaf come from? You can't see the answer — it is invisible." Post the driving question, and warn students the usual guess ("from the soil") is a trap.`},
    explore:{title:"Explore — invent your own words",estimatedMinutes:18,materials:["Pondweed","Lamp","Beaker"],
      teacherInstructions:`Groups watch pondweed under a bright lamp release a steady stream of gas bubbles — and stop when the lamp is switched off. Looking at the leaves and the phenomenon, they INVENT their own made-up word for: (1) the invisible gas the plant takes from the air, (2) the green stuff that captures light, (3) the whole light-powered food-making process, (4) the food it makes, and (5) the gas it gives off. Using only their words, they record what changes when light is present versus absent. Do NOT give the real terms yet.`},
    explain:{title:"Explain — reveal the real names",estimatedMinutes:14,materials:["Class lexicon chart"],
      teacherInstructions:`Groups share and explain, in their own language, that light powers the leaf to build food and release a gas. Build a class chart, then reveal each real term beside the invented one: carbon dioxide, chlorophyll, photosynthesis, glucose and oxygen. Land the big idea: the tree's mass comes mostly from carbon dioxide in the AIR (plus water), not from the soil.`},
    elaborate:{title:"Elaborate — test the light claim",estimatedMinutes:10,materials:["A dark-kept leaf","A foil-covered leaf"],
      teacherInstructions:`Predict-then-check: what happens to the pondweed bubbles (or a leaf) with NO light? Groups reason that if light is the energy source, food-making should stop. Discuss a leaf partly covered with foil and why only the lit part makes food, explaining with both invented and real terms.`},
    evaluate:{title:"Evaluate — explain it two ways",estimatedMinutes:5,materials:["Exit slip"],
      teacherInstructions:`Exit ticket: (1) In your invented words AND the real terms, explain where a tree's mass really comes from. (2) Predict what happens to food-making if a plant is kept in the dark, and explain why.`}
  },
  {
    style:"threshold",
    match:["solution","solute","solvent","dissolve","dissolving","concentration","concentrated","saturated","mixture"],
    activityTitle:"Name the Vanishing: Solutions from Scratch",
    sort:{"items": ["Sugar stirred into warm water", "Sand stirred into water", "Salt added to cold water until no more will go in", "Food colouring in water", "Chalk dust in water", "Sugar stirred into hot water"], "task": "Sort these by what happens to the added substance, then sort them again by whether the mixture stops accepting more — and name what your second sort is tracking."},
    poe:{"scenario": "A spoonful of sugar stirred into water, with the whole beaker weighed before and after.", "tempting": "That the mass will drop, because the sugar has gone."},
    counter:{"claim": "If you keep stirring, any amount of sugar will eventually dissolve.", "hunt": "Find the point where it stops — then find the change that makes stirring work again, and say what the claim ignored."},
    model:{"build": "Model the water as a car park with a fixed number of spaces, and the solute as cars looking for one.", "test": "Ask what heating does to the car park, then check it against how much extra sugar hot water really takes."},
    liminal:{"looks": ["Say the solute is gone or has become the liquid", "Expect the mass to drop after dissolving", "Keep adding solute past saturation, expecting it to disappear too", "Treat 'strong' and 'a lot of liquid' as the same thing"], "sounds": ["It disappeared.", "It turned into water.", "It's gone, so it must weigh less now.", "Why won't any more go in? It's broken."], "hold": ["Do not say 'dissolved, not destroyed'. Weigh before and after, let the unchanged number contradict them, then ask what that means.", "Ask 'if it's gone, why is it still sweet?' and wait.", "When they hit saturation, do not explain it — ask them to predict what heating will do and let them find that the limit moves.", "Ask them to draw where the solute is now, at the smallest scale they can imagine."]},
    transfer:{"when": "A later lesson, in everyday and industrial contexts.", "task": "Ask why sugar dissolves faster in hot tea, why cooling syrup grows crystals, why salt is spread on icy roads, and why a fizzy drink goes flat faster when warm.", "lookFor": "Whether they use concentration and a temperature-dependent limit, rather than 'it disappears' or 'heat makes things faster'."},
    progression:{"preliminal": "Believes the solute disappears or turns into the liquid; expects the mass to decrease.", "liminal": "Accepts that the solute is still present but cannot yet link concentration to amount, or explain why dissolving stops.", "crossed": "Explains concentration as solute per amount of solvent, and predicts that heating raises how much will dissolve.", "integrated": "Applies concentration and saturation to unfamiliar situations including crystallisation and gases, reasoning about the particle-level picture."},
    troublesome:"The dissolved solute hasn't vanished — it is still there, spread among the water particles; and a given amount of water can only hold so much, a limit that rises with temperature.",
    rule:"The more solute dissolved in a fixed amount of solvent, the more concentrated the solution; heating the solvent lets it hold (dissolve) more solute.",
    drivingQuestion:"When you stir something into water until it 'disappears', where does it go — and can you ever add too much?",
    ageBand:"Grade 7 (age 12) · Ages 12–14", totalMinutes:55,
    learningObjective:"Students will be able to explain concentrated solutions and how heating a concentrated solution lets more solute dissolve, after inventing their own names for the solvent, solute, and solution.",
    keyVocabulary:["solvent","solute","solution","concentration","saturated"],
    materialsList:["Clear cups of water","Salt or sugar (plenty)","Teaspoons & stirrers","'Our invented words' sheet","Hot water / hotplate (teacher-controlled)","Dark paper to view crystals"],
    lexicon:[
      {slot:"The liquid that does the dissolving (the water)",reveal:"solvent"},
      {slot:"The stuff you stir in that seems to vanish",reveal:"solute"},
      {slot:"The clear mixture you end up with",reveal:"solution"},
      {slot:"How crowded / packed the mixture is",reveal:"concentration"},
      {slot:"When it cannot swallow any more",reveal:"saturated"}
    ],
    engage:{title:"Engage — the disappearing act",estimatedMinutes:8,materials:["Clear cup of water","Salt or sugar"],
      teacherInstructions:`Stir a spoon of salt into a clear cup of water until it vanishes. Ask: "Where did it go? Is it gone?" Add another spoon, and another, stirring each time — until a spoon finally will NOT disappear and sits on the bottom. Ask: "Why did the early spoons vanish but this one won't? Can water take an unlimited amount?" Post the driving question, and tell students they will figure it out — and they get to NAME everything themselves.`},
    explore:{title:"Explore — invent your own words",estimatedMinutes:16,materials:["Cups of water","Salt/sugar","Spoons","'Our invented words' sheet"],
      teacherInstructions:`Each group makes their own mixtures and INVENTS a brand-new made-up word for each of these: (1) the liquid that dissolves things, (2) the stuff that vanishes into it, (3) the clear mixture that results, and (4) how "crowded" the mixture feels. They write their words on the sheet and may use ONLY their own words. Challenge: keep adding the vanishing-stuff until no more will disappear, and coin a word for that "full up" state. Circulate and ask them to describe what they see in their own language — do NOT give the real terms yet.`},
    explain:{title:"Explain — reveal the real names",estimatedMinutes:12,materials:["Class lexicon chart"],
      teacherInstructions:`Each group shares its invented words and explains, in their own language, that stirring in more vanishing-stuff makes the mixture more "crowded". Build a class chart. NOW reveal each real term and write it next to the word students already invented: solvent (their liquid-word), solute (their vanishing-word), solution (their mixture-word), concentration (their crowded-word), saturated (their full-up word). Define a concentrated solution as a lot of solute for the amount of solvent, and dilute as only a little.`},
    elaborate:{title:"Elaborate — heat a concentrated solution",estimatedMinutes:14,materials:["Hot water (teacher-controlled)","A saturated solution from Explore"],
      teacherInstructions:`Take a group's saturated, concentrated solution that still has undissolved solute on the bottom. Predict: "If we warm it, what happens to the leftover solute?" Gently heat it (teacher-controlled) — the extra solute dissolves, because the hot solvent can hold MORE. Students explain using their framework: heat lets the solvent hold more solute, so the concentration can go higher. Then let it cool and watch crystals of solute reappear as the solution can no longer stay that concentrated.`},
    evaluate:{title:"Evaluate — explain it two ways",estimatedMinutes:5,materials:["Exit slip"],
      teacherInstructions:`Exit ticket: (1) In your OWN invented words AND the real terms, explain what a concentrated solution is. (2) Predict what happens if you heat a concentrated solution that still has solute sitting on the bottom, and explain WHY. Check that both explanations match.`}
  },
  {
    match:["triangle inequality","three side","3 side","properties of a triangle","triangle"],
    activityTitle:"The Broken Ruler Triangle Challenge",
    drivingQuestion:"Can any three side lengths make a triangle?",
    ageBand:"Grade 6 (age 11)", totalMinutes:50,
    learningObjective:"Students will be able to predict and justify whether three given side lengths can form a triangle, discovering the triangle inequality rule.",
    keyVocabulary:["side length","triangle inequality","conjecture","rule / generalization"],
    materialsList:["Uncooked spaghetti or paper strips","Rulers","Recording table (handout)","Scissors"],
    engage:{title:"The impossible triangle",estimatedMinutes:7,materials:["3 pre-cut strips: 3 cm, 4 cm, 10 cm"],
      teacherInstructions:"Hold up three strips (3 cm, 4 cm, 10 cm) and say: \"I need a triangle from exactly these three pieces — no cutting.\" Try to build it in front of the class; the short sides won't meet. Ask: \"Is this just me being clumsy, or is something going on? Can ANY three lengths make a triangle?\" Post the driving question."},
    explore:{title:"Build, test, record",estimatedMinutes:18,materials:["Spaghetti/strips","Rulers","Recording table"],
      teacherInstructions:"In pairs, students cut pieces to given length-sets (mix of \"works\" and \"fails\"), attempt to form a closed triangle, and record Yes/No plus the three lengths in a table. Give at least 6 sets, e.g. (5,5,5),(4,4,9),(6,8,10),(2,3,8),(7,7,3),(5,6,10). Circulate; do NOT reveal the rule."},
    explain:{title:"Find the pattern",estimatedMinutes:12,materials:["Class data table"],
      teacherInstructions:"Collect results on the board. Ask groups: \"Look only at the sets that WORKED. What do the two shorter sides do compared to the longest?\" Guide them to articulate: the two shorter sides added together must be longer than the longest side. Introduce the term triangle inequality and the notation a + b > c."},
    elaborate:{title:"Design a fail",estimatedMinutes:8,materials:[],
      teacherInstructions:"Challenge: \"Give me one set that just BARELY works and one that just barely fails.\" Students test the boundary (e.g. 5,5,10 — degenerate) and discuss what happens exactly when a+b=c. Extend: given two sides of 6 and 9, what whole-number lengths can the third side be?"},
    evaluate:{title:"Exit ticket",estimatedMinutes:5,materials:["Exit slip"],
      teacherInstructions:"On a slip, each student answers: (1) Can 4, 6, and 11 form a triangle? Show why. (2) Two sides are 8 and 5 — give a third length that works and one that doesn't. Collect as a quick check for the rule."}
  },
  {
    match:["seasons","why do we have seasons","tilt","axial"],
    activityTitle:"Chasing the Sun's Angle",
    drivingQuestion:"Why is it hot in summer and cold in winter — is Earth just closer to the Sun?",
    ageBand:"Grade 4 (age 9)", totalMinutes:50,
    learningObjective:"Students will be able to explain that seasons are caused by Earth's tilt changing how directly sunlight hits a place, not by distance from the Sun.",
    keyVocabulary:["tilt","direct vs. slanted light","axis","season"],
    materialsList:["Flashlight or lamp","Globe or ball + skewer","Graph paper","Thermometers (optional)"],
    engage:{title:"The distance trap",estimatedMinutes:8,materials:["Globe","Flashlight"],
      teacherInstructions:"Ask: \"Who thinks summer happens because Earth moves closer to the Sun?\" Take a vote. Then reveal: when it's summer in the US, it's winter in Australia — at the SAME time, same distance. \"So distance can't be the whole story. What IS different?\" Post the driving question."},
    explore:{title:"Direct vs. slanted light",estimatedMinutes:16,materials:["Flashlight","Graph paper"],
      teacherInstructions:"In groups, shine a flashlight straight down onto graph paper, then at a low slant. Trace the lit patch each time and count the squares covered. Record: which spreads the same light over MORE squares? Which squares are brighter? Connect brighter/concentrated = warmer."},
    explain:{title:"Tilt tells the story",estimatedMinutes:14,materials:["Globe + skewer"],
      teacherInstructions:"Using a tilted globe orbiting a lamp, show that the tilt makes sunlight hit the top half directly in June (summer) and slanted in December (winter). Students explain in their own words, then you formalize: Earth's axis is tilted; the hemisphere tilted toward the Sun gets direct light = summer."},
    elaborate:{title:"Where on Earth?",estimatedMinutes:7,materials:["Globe"],
      teacherInstructions:"Ask: \"Using tilt, why is it always hot near the equator and cold at the poles?\" Groups reason with the globe and light. Extend to why summer days are longer."},
    evaluate:{title:"Explain to a friend",estimatedMinutes:5,materials:["Half-sheet"],
      teacherInstructions:"Students write a 3-sentence note to a friend who thinks seasons come from distance, using the words tilt and direct light to correct them. Quick read for the misconception."}
  },
  {
    match:["fair test","variable","controlled experiment","fair experiment"],
    activityTitle:"The Suspicious Science Claim",
    drivingQuestion:"What makes an experiment a fair test — and how can two people get different answers to the same question?",
    ageBand:"Grade 5 (age 10)", totalMinutes:45,
    learningObjective:"Students will be able to design a fair test by changing one variable while keeping all others the same.",
    keyVocabulary:["variable","fair test","control","keep-the-same"],
    materialsList:["Paper for paper planes","Ramps + toy cars (optional)","Recording sheet","Tape/rulers"],
    engage:{title:"Two rival claims",estimatedMinutes:7,materials:["2 paper planes"],
      teacherInstructions:"Show two paper planes and claim: \"Plane A flies farther than Plane B — proof that pointy noses are best.\" Then reveal you threw A much harder and from higher up. Ask: \"Do we actually KNOW noses matter? What went wrong?\" Post the driving question."},
    explore:{title:"Break the test on purpose",estimatedMinutes:15,materials:["Paper planes","Rulers"],
      teacherInstructions:"Groups test which paper affects distance, but you secretly assign each group a DIFFERENT sloppy method (change thrower, height, and paper all at once). Compare class results — they wildly disagree. Students record what each group changed."},
    explain:{title:"One thing at a time",estimatedMinutes:13,materials:["Recording sheet"],
      teacherInstructions:"Discuss why results disagreed. Guide to the rule: change only ONE thing (the variable you're testing) and keep everything else the same. Introduce variable, control, and fair test. Redesign the plane test together with a keep-the-same list."},
    elaborate:{title:"Fix a flawed test",estimatedMinutes:6,materials:["Flawed-test cards"],
      teacherInstructions:"Give each group a card describing a flawed experiment (e.g. \"Does plant food help? We gave the big plant food and the small one none.\"). They identify what's unfair and how to fix it."},
    evaluate:{title:"Spot the flaw",estimatedMinutes:4,materials:["Exit slip"],
      teacherInstructions:"Exit slip: \"A student says warm water dissolves sugar faster, but they also stirred the warm cup more. Is this a fair test? What must they keep the same?\""}
  },
  {
    match:["supply and demand","supply & demand","price","market","economics"],
    activityTitle:"The Classroom Market Crash",
    drivingQuestion:"Who actually decides the price of something — the seller, the buyer, or neither?",
    ageBand:"Grade 10 (age 15)", totalMinutes:55,
    learningObjective:"Students will be able to explain how the interaction of supply and demand determines equilibrium price, using data from a simulated market.",
    keyVocabulary:["supply","demand","equilibrium","shortage","surplus"],
    materialsList:["Role cards (buyers/sellers)","Play money or tokens","Whiteboard for price log","Graph paper / plotting tool"],
    engage:{title:"Name your price",estimatedMinutes:8,materials:["A single desirable item"],
      teacherInstructions:"Auction one genuinely wanted item (front-row seat pass, homework pass). Watch the price climb. Then say: \"If I had 30 of these, what happens to the price?\" Provoke the tension between what sellers want and what buyers will pay. Post the driving question."},
    explore:{title:"Run a live market",estimatedMinutes:20,materials:["Role cards","Tokens"],
      teacherInstructions:"Assign buyers a maximum price and sellers a minimum price on secret cards. Run several trading rounds; students negotiate deals and you log every agreed price on the board. Repeat, then add more sellers (increase supply) and observe."},
    explain:{title:"Where prices settle",estimatedMinutes:15,materials:["Price log","Graph paper"],
      teacherInstructions:"Plot the logged prices; they cluster around a value. Have students articulate why deals above buyers' max or below sellers' min never happened. Formalize supply, demand, and equilibrium — the price where quantity wanted equals quantity offered. Define shortage and surplus."},
    elaborate:{title:"Shock the market",estimatedMinutes:8,materials:[],
      teacherInstructions:"Introduce a shock (e.g. a shortage: half the sellers leave; or a demand spike). Students predict, then re-run one round to test the price movement and explain the shift using the model."},
    evaluate:{title:"Predict & justify",estimatedMinutes:4,materials:["Exit slip"],
      teacherInstructions:"Exit slip: \"A frost destroys half the coffee crop. Using supply and demand, predict what happens to the price and explain why in 2–3 sentences.\""}
  },
  {
    match:["poem","poetry","what makes a poem","language arts"],
    activityTitle:"Is This a Poem?",
    drivingQuestion:"What makes a poem feel like a poem — and can a grocery list ever be one?",
    ageBand:"Grade 3 (age 8)", totalMinutes:40,
    learningObjective:"Students will be able to identify features that make writing feel like a poem (sound, line breaks, imagery, feeling) and use one to write their own.",
    keyVocabulary:["line","rhythm","image","feeling"],
    materialsList:["Short poems on cards","A real grocery list","Crayons/paper","Chart paper"],
    engage:{title:"Poem or not?",estimatedMinutes:7,materials:["Poem cards","Grocery list"],
      teacherInstructions:"Read aloud a tiny vivid poem, then read a plain grocery list in the same voice. Ask: \"Which one was a poem? How did you KNOW?\" Let kids blurt reasons. Post the driving question and keep a running list of their clues."},
    explore:{title:"Sort the mystery texts",estimatedMinutes:12,materials:["Mixed text cards"],
      teacherInstructions:"Groups get a stack of cards — some poems, some sentences, some lists — and sort them into \"feels like a poem\" and \"doesn't.\" They must whisper-argue and agree. Circulate and ask \"what made you put it there?\" Do not give the answer."},
    explain:{title:"Our poem clues",estimatedMinutes:10,materials:["Chart paper"],
      teacherInstructions:"Build a class chart from their reasons. Nudge toward: poems paint a picture (image), can have rhythm or sound, use short lines, and give a feeling. Name these gently. Show how the grocery list COULD become a poem by adding an image and line breaks."},
    elaborate:{title:"Turn something plain into a poem",estimatedMinutes:8,materials:["Paper","Crayons"],
      teacherInstructions:"Each child takes a boring sentence (\"I ate breakfast\") and turns it into a 3-line mini-poem using one clue from the chart (an image or a sound). Volunteers share."},
    evaluate:{title:"Thumbs & tell",estimatedMinutes:3,materials:[],
      teacherInstructions:"Read two short texts; students thumbs-up if it's a poem and name ONE clue that tells them. Quick check of the features."}
  },
  {
    match:["moon phases","phases of the moon","why does the moon change","lunar"],
    activityTitle:"The Moon's Changing Face",
    drivingQuestion:"Why does the Moon change shape — is something covering it up?",
    ageBand:"Grade 5 (age 10)", totalMinutes:45,
    learningObjective:"Students will be able to model how the Moon's phases result from sunlight hitting it as it orbits Earth, not from a shadow covering it.",
    keyVocabulary:["phase","orbit","reflect","crescent / gibbous"],
    materialsList:["Foam balls on sticks","A bright lamp","Darkenable room","Phase recording circle"],
    engage:{title:"The shrinking Moon myth",estimatedMinutes:7,materials:["Moon photos"],
      teacherInstructions:"Show a sequence of Moon photos across a month. Offer a wrong idea: \"Maybe Earth's shadow eats the Moon a bit each night.\" Ask: \"Does that hold up? Then why is a crescent CURVED the way it is?\" Post the driving question."},
    explore:{title:"Model it in the dark",estimatedMinutes:16,materials:["Foam ball","Lamp"],
      teacherInstructions:"Each student holds a ball (Moon) at arm's length and slowly turns in place with a single lamp (Sun) lighting the room. They observe how the lit part they can see changes — full, half, crescent — and sketch what they see at 8 positions."},
    explain:{title:"It's about the angle of light",estimatedMinutes:14,materials:["Recording circle"],
      teacherInstructions:"Students compare sketches. Guide them: the Moon is always half-lit by the Sun; we just see different amounts as it orbits. Rule out the shadow idea (shadow only causes rare eclipses). Introduce phase, orbit, reflect, and phase names."},
    elaborate:{title:"Predict the next phase",estimatedMinutes:5,materials:["Calendar"],
      teacherInstructions:"Given tonight's phase, groups predict what it will look like in one week and justify using their model. Connect to why we see the same face of the Moon."},
    evaluate:{title:"Draw & explain",estimatedMinutes:3,materials:["Exit slip"],
      teacherInstructions:"Exit slip: draw a crescent Moon and write one sentence explaining what causes it, using the words orbit and light."}
  }
];
